#!/bin/bash

bspc monitor -d I II III IV V


killall -q polybar
pkill sxhdk
polybar --config=/home/izac/.config/polybar/config.ini &
sxhkd &
#tint2 &
bspc config border_width 0
bspc config window_gap 2
bspc config focused_border_color "#a6e3a1"

# feh --bg-scale /home/izac/Downloads/rectangle.png
feh --bg-scale /home/izac/Downloads/bg4.png

picom &

exec bspwm
